import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      // Material You color tokens — extracted from Stitch design references
      colors: {
        primary:                   '#00696b',
        'on-primary':              '#ffffff',
        'primary-container':       '#74c7c8',
        'on-primary-container':    '#005354',
        'primary-fixed':           '#9df1f2',
        'primary-fixed-dim':       '#81d4d5',
        'on-primary-fixed':        '#002020',
        'on-primary-fixed-variant':'#004f51',
        secondary:                 '#006a6a',
        'on-secondary':            '#ffffff',
        'secondary-container':     '#8cf3f3',
        'on-secondary-container':  '#007070',
        'secondary-fixed':         '#8cf3f3',
        'secondary-fixed-dim':     '#6fd7d6',
        'on-secondary-fixed':      '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        tertiary:                  '#725c06',
        'on-tertiary':             '#ffffff',
        'tertiary-container':      '#d4b75e',
        'on-tertiary-container':   '#5a4800',
        'tertiary-fixed':          '#ffe085',
        'tertiary-fixed-dim':      '#e2c469',
        'on-tertiary-fixed':       '#231b00',
        'on-tertiary-fixed-variant':'#574500',
        error:                     '#ba1a1a',
        'on-error':                '#ffffff',
        'error-container':         '#ffdad6',
        'on-error-container':      '#93000a',
        background:                '#f8f9ff',
        'on-background':           '#0b1c30',
        surface:                   '#f8f9ff',
        'surface-dim':             '#cbdbf5',
        'surface-bright':          '#f8f9ff',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#eff4ff',
        'surface-container':       '#e5eeff',
        'surface-container-high':  '#dce9ff',
        'surface-container-highest':'#d3e4fe',
        'surface-variant':         '#d3e4fe',
        'on-surface':              '#0b1c30',
        'on-surface-variant':      '#3b4949',
        'surface-tint':            '#00696b',
        outline:                   '#6b7a7a',
        'outline-variant':         '#bac9c9',
        'inverse-surface':         '#213145',
        'inverse-on-surface':      '#eaf1ff',
        'inverse-primary':         '#81d4d5',
        // keep shadcn tokens for any remaining components
        foreground:                '#0b1c30',
        border:                    '#bac9c9',
        input:                     '#bac9c9',
        ring:                      '#00696b',
        muted:                     '#e5eeff',
        destructive:               '#ba1a1a',
      },
      fontFamily: {
        // Quicksand for display & headline
        display:    ['var(--font-quicksand)', 'system-ui', 'sans-serif'],
        headline:   ['var(--font-quicksand)', 'system-ui', 'sans-serif'],
        // Inter for body, label, data
        body:       ['var(--font-inter)', 'system-ui', 'sans-serif'],
        label:      ['var(--font-inter)', 'system-ui', 'sans-serif'],
        sans:       ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono:       ['ui-monospace', 'Menlo', 'monospace'],
        monoton:    ['var(--font-monoton)', 'cursive'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile':['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':          ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm':          ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption:             ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
        gutter: '16px',
        'section-gap': '40px',
        base: '8px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
