import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      // Material You color tokens — teal + white + amber palette
      colors: {
        primary:                   '#0F766E',
        'on-primary':              '#ffffff',
        'primary-container':       '#CCFBF1',
        'on-primary-container':    '#134E4A',
        'primary-fixed':           '#CCFBF1',
        'primary-fixed-dim':       '#99F6E4',
        'on-primary-fixed':        '#042F2E',
        'on-primary-fixed-variant':'#0F766E',
        secondary:                 '#D97706',
        'on-secondary':            '#ffffff',
        'secondary-container':     '#FEF3C7',
        'on-secondary-container':  '#78350F',
        'secondary-fixed':         '#FEF3C7',
        'secondary-fixed-dim':     '#FDE68A',
        'on-secondary-fixed':      '#451A03',
        'on-secondary-fixed-variant': '#92400E',
        tertiary:                  '#D97706',
        'on-tertiary':             '#ffffff',
        'tertiary-container':      '#FEF3C7',
        'on-tertiary-container':   '#78350F',
        'tertiary-fixed':          '#FEF3C7',
        'tertiary-fixed-dim':      '#FDE68A',
        'on-tertiary-fixed':       '#451A03',
        'on-tertiary-fixed-variant':'#92400E',
        error:                     '#DC2626',
        'on-error':                '#ffffff',
        'error-container':         '#FEE2E2',
        'on-error-container':      '#991B1B',
        background:                '#ffffff',
        'on-background':           '#0A0A0A',
        surface:                   '#ffffff',
        'surface-dim':             '#E4E4E7',
        'surface-bright':          '#ffffff',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#FAFAFA',
        'surface-container':       '#FAFAFA',
        'surface-container-high':  '#F4F4F5',
        'surface-container-highest':'#E4E4E7',
        'surface-variant':         '#F4F4F5',
        'on-surface':              '#0A0A0A',
        'on-surface-variant':      '#52525B',
        'surface-tint':            '#0F766E',
        outline:                   '#71717A',
        'outline-variant':         '#E4E4E7',
        'inverse-surface':         '#18181B',
        'inverse-on-surface':      '#FAFAFA',
        'inverse-primary':         '#5EEAD4',
        // keep shadcn tokens for any remaining components
        foreground:                '#0A0A0A',
        border:                    '#E4E4E7',
        input:                     '#E4E4E7',
        ring:                      '#0F766E',
        muted:                     '#F4F4F5',
        destructive:               '#DC2626',
      },
      fontFamily: {
        // Quicksand for display & headline
        display:    ['var(--font-quicksand)', 'system-ui', 'sans-serif'],
        headline:   ['var(--font-quicksand)', 'system-ui', 'sans-serif'],
        // Inter for body, label, data
        body:       ['var(--font-inter)', 'system-ui', 'sans-serif'],
        label:      ['var(--font-inter)', 'system-ui', 'sans-serif'],
        sans:       ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono:       ['ui-monospace', 'Menlo', 'monospace'],
        monoton:    ['var(--font-monoton)', 'cursive'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile':['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':          ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm':          ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption:             ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
        gutter: '16px',
        'section-gap': '40px',
        base: '8px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
